import { db, Timeline } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
	await db.insert(Timeline).values([
		{
			"_index": 1,
			"uid": "451c1cd49a2f955d",
			"instance_type": "m1.small",
			"instance_category": "General Purpose",
			"instance_generation": "Previous generation",
			"release_month": "August",
			"release_year": 2006,
			"product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2006/08/24/announcing-amazon-elastic-compute-cloud-amazon-ec2---beta/",
			"announcement_published": "Aug 24, 2006",
			"blog_post_url": null,
			"blog_post_published": null,
		},
		{
			"_index": 2,
			"uid": "85589f23e811f229",
			"instance_type": "m1.large",
			"instance_category": "General Purpose",
			"instance_generation": "Previous generation",
			"release_month": "October",
			"release_year": 2007,
			"product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2007/10/22/amazon-ec2-now-in-unlimited-beta-and-launching-new-instance-types/",
			"announcement_published": "Oct 22, 2007",
			"blog_post_url": "https://aws.amazon.com/blogs/aws/amazon-ec2-gets/",
			"blog_post_published": "Oct 16, 2007",
		},
        {
            "_index": 3,
            "uid": "db881dc65b70a128",
            "instance_type": "m1.xlarge",
            "instance_category": "General Purpose",
            "instance_generation": "Previous generation",
            "release_month": "October",
            "release_year": 2007,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
            "announcement_url": "https://aws.amazon.com/about-aws/whats-new/2007/10/22/amazon-ec2-now-in-unlimited-beta-and-launching-new-instance-types/",
            "announcement_published": "Oct 22, 2007",
            "blog_post_url": "https://aws.amazon.com/blogs/aws/amazon-ec2-gets/",
            "blog_post_published": "Oct 16, 2007",
        },
        {
            "_index": 4,
            "uid": "719785bb62b69257",
            "instance_type": "c1.medium",
            "instance_category": "Compute Optimized",
            "instance_generation": "Previous generation",
            "release_month": "May",
            "release_year": 2008,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": null,
			"announcement_published": null,
			"blog_post_url": "https://aws.amazon.com/blogs/aws/more-ec2-power/",
			"blog_post_published": "May 29, 2008",

        },
        {
            "_index": 5,
            "uid": "14861a4162144a39",
            "instance_type": "c1.xlarge",
            "instance_category": "Compute Optimized",
            "instance_generation": "Previous generation",
            "release_month": "May",
            "release_year": 2008,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": null,
			"announcement_published": null,
			"blog_post_url": "https://aws.amazon.com/blogs/aws/more-ec2-power/",
			"blog_post_published": "May 29, 2008",
        },
        {
            "_index": 6,
            "uid": "0204afdbb01d1e39",
            "instance_type": "m2.2xlarge",
            "instance_category": "Memory Optimized",
            "instance_generation": "Previous generation",
            "release_month": "October",
            "release_year": 2009,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2009/10/27/announcing-amazon-ec2-high-memory-instances/",
			"announcement_published": "Oct 27, 2009",
			"blog_post_url": "https://aws.amazon.com/blogs/aws/new-ec2-instance-type-m2xlarge/",
			"blog_post_published": "Oct 27, 2009",
        },
        {
            "_index": 7,
            "uid": "402230d55ac40b3d",
            "instance_type": "m2.4xlarge",
            "instance_category": "Memory Optimized",
            "instance_generation": "Previous generation",
            "release_month": "October",
            "release_year": 2009,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2009/10/27/announcing-amazon-ec2-high-memory-instances/",
			"announcement_published": "Oct 27, 2009",
			"blog_post_url": "https://aws.amazon.com/blogs/aws/new-ec2-instance-type-m2xlarge/",
			"blog_post_published": "Oct 27, 2009",
        },
        {
            "_index": 8,
            "uid": "47d092273fc720af",
            "instance_type": "m2.xlarge",
            "instance_category": "Memory Optimized",
            "instance_generation": "Previous generation",
            "release_month": "February",
            "release_year": 2010,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2010/02/23/Amazon-EC2-Now-Offers-Extra-Large-High-Memory-Instances/",
			"announcement_published": "Feb 23, 2010",
			"blog_post_url": "https://aws.amazon.com/blogs/aws/new-ec2-instance-type-m2xlarge/",
			"blog_post_published": "Feb 22, 2010",
        },
        {
            "_index": 9,
            "uid": "6fabd67a7645aa5b",
            "instance_type": "cc1.4xlarge",
            "instance_category": "Cluster Compute",
            "instance_generation": "Previous generation",
            "release_month": "July",
            "release_year": 2010,
            "product_page": null,
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2010/07/13/announcing-cluster-compute-instances-for-amazon-ec2/",
			"announcement_published": "Jul 13, 2010",
			"blog_post_url": "https://aws.amazon.com/blogs/aws/the-new-amazon-ec2-instance-type-the-cluster-compute-instance/",
			"blog_post_published": "Jul 13, 2010",
        },
        {
            "_index": 10,
            "uid": "a4004d9227d252bb",
            "instance_type": "t1.micro",
            "instance_category": "Micro",
            "instance_generation": "Previous generation",
            "release_month": "September",
            "release_year": 2010,
            "product_page": "https://aws.amazon.com/ec2/previous-generation/",
			"announcement_url": "https://aws.amazon.com/about-aws/whats-new/2010/09/09/announcing-micro-instances-for-amazon-ec2/",
			"announcement_published": "Sep 9, 2010",
			"blog_post_url": "https://aws.amazon.com/blogs/aws/new-amazon-ec2-micro-instances/",
			"blog_post_published": "Sep 09, 2010",
        }
	]);
}